name: Publishing

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  cancel-previous:
    name: Cancel Publishing
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Build
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish
        run: echo "Publishing triggered via a tag"
